export const ADD_ENTRAINEMENT = "ADD_ENTRAINEMENT";
export const FOUND_BAD_WORD = "FOUND_BAD_WORD";
export const DELETE_ENTRAINEMENT = "DELETE_ENTRAINEMENT";
export const LOAD_DATA = "DELETE_ENTRAINEMENT";
